export {default as BackendJs} from './back end js pemula-1.png';
export {default as Jaringan} from './JARINGAN .png';
export {default as javaOracle} from './Java Fundamental ranto.png';
export {default as Aws} from './ranto aws.png';
export {default as C} from './ranto bahasa c.png';
export {default as DataBaseDesign} from './ranto database  design.png';
export {default as DevOps} from './ranto dev ops.png';
export {default as Github} from './ranto github-1.png';
export {default as javaDicoding} from './ranto java -1.png';
export {default as ReactAltera} from './react-altera.png';
export {default as PhpKominfo} from './unior Web Developer.png';
