const Data = [
  {
    name: "Kpoin app",
    link: "https://app.kpoin.com/",
    icons: "/assets/icons/nextjs.svg",
    hastag: "#Nextjs #MantineUI #Tailwindcss",
    status: "public",
  },
  {
    name: "Landing Page Kpoin",
    link: "https://kpoin.com/",
    icons: "/assets/icons/nextjs.svg",
    hastag: "#Nextjs #MantineUI #Tailwindcss",
    status: "public",
  },
  {
    name: "Event Kpoin",
    link: "https://event.kpoin.com/",
    icons: "/assets/icons/nextjs.svg",
    hastag: "#Nextjs #MantineUI #Tailwindcss",
    status: "public",
  },
  {
    name: "Event Kpoin",
    link: "https://event.kpoin.com/",
    icons: "/assets/icons/nextjs.svg",
    hastag: "#Nextjs #MantineUI #Tailwindcss",
    status: "public",
  },
  {
    name: "Leanding Page PG",
    link: "https://leanding-page-payment-gateway.vercel.app/",
    icons: "/assets/icons/react.svg",
    hastag: "#ReactJs #LeandingPagePG",
    status: "public",
  },
  {
    name: "Rans Information",
    link: "https://portofolio-ranto12.vercel.app/",
    icons: "/assets/icons/nextjs.svg",
    hastag: "#NextJs #Portofolio",
    status: "public",
  },
  {
    name: "Desin Pettern",
    link: "https://github.com/Ranto12/design-pattern",
    icons: "/assets/icons/github.svg",
    hastag: "#ReactJs #nodeJs #DesignPetter",
    status: "public",
  },
  {
    name: "teknik digital",
    link: "https://teknik-digital.vercel.app/",
    icons: "/assets/icons/MaterializeCSS.svg",
    hastag: "#Javascript #MaterializeCSS",
    status: "public",
  },
  {
    name: "kuis online",
    link: "https://62d5aeea5f7f8c311b7e5b10--dot-ranto-magang.netlify.app/",
    icons: "/assets/icons/react.svg",
    hastag: "#Javascript #bootstrap",
    status: "public",
  },
  {
    name: "kalkulator",
    link: "https://calculator-ranto12.vercel.app/",
    icons: "/assets/icons/html.svg",
    hastag: "#Javascript #html",
    status: "public",
  },
  {
    name: "Vaksin Yuk",
    link: "https://vaksin-yuk.vercel.app",
    icons: "/assets/icons/react.svg",
    hastag: "#ReactJs #bootstrap",
    status: "private",
  },
  {
    name: "CRUD PHP",
    link: "https://crudphpranto.000webhostapp.com/",
    icons: "/assets/icons/php.svg",
    hastag: "#PHP #MYSQL",
    status: "public",
  },
  {
    name: "Leanding product",
    link: "https://leangding-product.vercel.app/",
    icons: "/assets/icons/nextjs.svg",
    hastag: "#nextjs #tailwidcss",
    status: "public",
  },
  {
    name: "PUMMA Information",
    link: "https://pumma.isi-net.org",
    icons: "/assets/icons/react.svg",
    hastag: "#ReactJs #iot",
    status: "public",
  },
  {
    name: "payment Gateway",
    link: "https://dashboardquipay.vercel.app",
    icons: "/assets/icons/react.svg",
    hastag: "#ReactJs #paymentgetway",
    status: "public",
  },
];

export default Data;
